export const adminFaqs = [
  {
    id: 1,
    question: "How do I renew my licence?",
    answer:
      "You can renew your licence through the official NMCN licence portal. Follow the renewal instructions, complete the required steps, and ensure payment is made through the approved channel.",
    category: "Licensing",
    status: "Published",
    updatedAt: "2026-04-08",
    featured: true,
    keywords: "renewal, licence, portal",
    relatedLinkLabel: "Open Licence Portal",
    relatedLinkUrl: "https://licence.nmcn.gov.ng/",
  },
  {
    id: 2,
    question: "I forgot my password. What should I do?",
    answer:
      "Use the password recovery option on the portal login page and follow the reset instructions provided there.",
    category: "Portal Access",
    status: "Published",
    updatedAt: "2026-04-07",
    featured: false,
    keywords: "password, login, reset",
    relatedLinkLabel: "Go to Licence Portal",
    relatedLinkUrl: "https://licence.nmcn.gov.ng/",
  },
  {
    id: 3,
    question: "How can I verify certificates?",
    answer:
      "Use the official verification service provided by NMCN through the website or service portal.",
    category: "Verification",
    status: "Draft",
    updatedAt: "2026-04-06",
    featured: false,
    keywords: "certificate, verification",
    relatedLinkLabel: "Visit Main Website",
    relatedLinkUrl: "https://nmcn.gov.ng/",
  },
  {
    id: 4,
    question: "What should I do if my registration number cannot be found?",
    answer:
      "If your registration number cannot be found, contact support so your record can be reviewed and confirmed by the Council.",
    category: "Registration",
    status: "Published",
    updatedAt: "2026-04-05",
    featured: true,
    keywords: "registration, number, profile",
    relatedLinkLabel: "Reach Support",
    relatedLinkUrl: "https://nmcn.gov.ng/reach-us/",
  },
  {
    id: 5,
    question: "Can I update my profile if my licence has not expired?",
    answer:
      "Yes. Nurses and midwives registered with NMCN are expected to keep their profile details updated even when the licence is still valid.",
    category: "Licensing",
    status: "Draft",
    updatedAt: "2026-04-04",
    featured: false,
    keywords: "profile, licence, update",
    relatedLinkLabel: "Open Licence Portal",
    relatedLinkUrl: "https://licence.nmcn.gov.ng/",
  },
];